### DISCUSSION TITLE
How to use with pool(some like deadpool)

### DISCUSSION THREAD

**Discussion by y0zong** [c410-f3r/wtx#215] [General]
hi, how to use Postgres with pool? both `deadpool` or `pool`(by **wtx** itself) is ok

**Comment by c410-f3r** [comment]
Hello,

In order to use the PostgreSQL client with built-in pools, you have to selected the `pool` and `postgres` features.

Here goes an example using `tokio` with 4 unencrypted PostgreSQL connections.

```toml
[dependencies]
wtx = { default-features = false, features = ["pool", "postgres", "tokio"], version = "0.17" }
tokio = { features = ["macros", "net", "rt-multi-thread"], version = "1.0" }
```

```rust
use std::sync::OnceLock;
use tokio::{net::TcpStream, sync::MutexGuard};
use wtx::{
  database::{
    client::postgres::{Executor, ExecutorBuffer},
    Executor as _, Record,
  },
  pool::{Pool, PostgresRM, SimplePoolGetElem, SimplePoolResource, SimplePoolTokio},
};

#[tokio::main]
async fn main() -> wtx::Result<()> {
  let mut lock = pool().await?;
  let record = lock.fetch_with_stmt("SELECT name FROM persons WHERE id = $1", (123456,)).await?;
  let name = record.decode::<_, &str>(0)?;
  println!("Name: {name}");
  Ok(())
}

async fn pool() -> wtx::Result<
  SimplePoolGetElem<
    MutexGuard<'static, SimplePoolResource<Executor<wtx::Error, ExecutorBuffer, TcpStream>>>,
  >,
> {
  static POOL: OnceLock<SimplePoolTokio<PostgresRM<wtx::Error, TcpStream>>> = OnceLock::new();
  POOL
    .get_or_init(|| {
      SimplePoolTokio::new(4, PostgresRM::tokio("postgres://USER:PASSWORD@localhost:5432/DB_NAME"))
    })
    .get(&(), &())
    .await
}
```

For more examples, take a look at https://github.com/c410-f3r/wtx/blob/main/wtx-instances/examples/http-server-framework-tokio.rs or https://github.com/c410-f3r/wtx/blob/main/wtx-instances/examples/database-client-postgres-tokio.rs.
